export const DOG_BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Beagle",
  "Pug",
  "Shih Tzu",
  "Poodle",
  "Rottweiler",
  "Doberman Pinscher",
  "Boxer",
  "Dachshund",
  "Cocker Spaniel",
  "Great Dane",
  "Siberian Husky",
  "Saint Bernard",
  "Bulldog",
  "French Bulldog",
  "Chihuahua",
  "Pomeranian",
  "Maltese",
  "Yorkshire Terrier",
  "Border Collie",
  "Australian Shepherd",
  "Boston Terrier",
  "Shiba Inu",
  "Akita",
  "Belgian Malinois",
  "Bull Terrier",
  "Cane Corso",
  "Chow Chow",
  "Dalmatian",
  "English Mastiff",
  "Greyhound",
  "Jack Russell Terrier",
  "Lhasa Apso",
  "Newfoundland",
  "Papillon",
  "Pointer",
  "Rhodesian Ridgeback",
  "Schnauzer",
  "Weimaraner",
  "Whippet",
  "Cavalier King Charles Spaniel",
  "Basset Hound",
  "Bernese Mountain Dog",
  "Indian Pariah Dog (Desi)",
  "Rajapalayam",
  "Mudhol Hound",
  "Kombai",
  "Chippiparai",
  "Himalayan Sheepdog",
  "Bakharwal Dog",
  "Mixed Breed / Indie",
  "Other",
] as const;

export const PET_SIZE_OPTIONS = [
  { value: "small", label: "Small (up to 10 kg)" },
  { value: "medium", label: "Medium (10–25 kg)" },
  { value: "large", label: "Large (25 kg+)" },
] as const;
